# Generated by Django 2.2 on 2019-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlVersion', models.CharField(max_length=50)),
                ('pageTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
