# Generated by Django 2.2 on 2019-04-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
